### Test Student Payment & Voucher Counter
POST http://127.0.0.1:5000/payments/stk_push
Content-Type: application/json

{
    "amount": 10,
    "student_name": "Ken",
    "rider_id": "rider_001",
    "phone": "254724474144"
}
